### PR TITLE
[scaling] Scaling of homescreen icons and applauncher

### PR DESCRIPTION
**Pull request by M2ko**

### CODE REVIEW

**Comment by faenil** [comment]
LGTM :) I didn't write the homescreen, but the changes look sensible, we shouldn't really be using hardcoded sizes :|

**Comment by M2ko** [comment]
These changes are made by eekkelund btw. :)

**Comment by faenil** [comment]
cool, thanks a lot for the contribution! :)

**Comment by locusf** [comment]
@eekkelund and @M2ko also gotta implement the scaling for the statusbar as well so I'll keep this open :)

**Comment by locusf** [comment]
Merging, other scaling done on other pull requests.

**Pull request merged**
