### PR TITLE
Fixup crazy font sizes in the app switcher

### PR DESCRIPTION
**Pull request by piggz**

### CODE REVIEW

**Comment by locusf** [comment]
Thank you!

**Comment by faenil** [comment]
we should fix ButtonStyle, if that needs fixing... :/

**Comment by piggz** [comment]
OK, I'll take a look..i dont want to break any other applications though. Do we need these custom components on top of standard qt?

**Comment by faenil** [comment]
what do you mean?

yes, Glacier UI components are currently using QtQuickControls1, and we have qtquickcontrols-nemo where all the style files live.

(The plan is to move to QtQuickControls2 as a base)

**Comment by piggz** [comment]
I meant why are glacier components needed a all?

**Comment by piggz** [comment]
I guess they are analogous to silica, but it seems like extra burden to maintain on top of qtquick controls.... devs have a target them specifically...from an app writing perspective it seems easier to have a common set of components to develop against

**Comment by faenil** [comment]
And then you have to convince everyone to develop using your new unitified components interface? :)
this problem is hard and it's been discussed multiple times on Qt ML as well...

Please note: Glacier components are just QQC+styling (and some extra component), so apps using QQC will just run. If they want the special glacier header (which is not a QQC component) they they'll have to add it

**Pull request merged**
