### PR TITLE
Port to CMake

### PR DESCRIPTION
**Pull request by PureTryOut**
qmake won't be developed anymore from Qt6 and they're switching to CMake, so let's do the same.

### CODE REVIEW

**Comment by PureTryOut** [comment]
Wait, why did you close this?

**Comment by neochapay** [comment]
Because devel branch is deleted

**Comment by JBBgameich** [comment]
FYI, it is possible to re-target pull requests to another branch.

**Comment by neochapay** [comment]
It closet automatically

**Pull request closed without merging**
