### PR TITLE
[WIP] [Welcome] Add welcome and first run proto

### PR DESCRIPTION
**Pull request by neochapay**
First run and welcome dialog must provide some hello page and

- select language
- select timezone
- setup wifi
- setup cellural
- etc

### CODE REVIEW

**Comment by PureTryOut** [comment]
Maybe it would be nice if distributions could provide some extra page with some distro specific information.

At postmarketOS we have our own welcoming app for Phosh and will probably make one for Plasma Mobile as well, giving some distro specific information we think is necessary to use our distribution. It would be nice if we could plug into an existing application in the case of Glacier/Nemo rather than making yet another specific application for this.

**Comment by neochapay** [comment]
Which information will be interest ?

**Comment by PureTryOut** [comment]
In case of a distribution like postmarketOS? Things like where to report bug reports, general usage information (like installing apps via command line), what the OS is at all, etc. It'll just be regular text, although maybe an image or two (I doubt it).

**Comment by neochapay** [comment]
Moved to https://github.com/nemomobile-ux/glacier-welcome

**Pull request closed without merging**
