### PR TITLE
[DeviceLock] Fix issue #67

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Comment by marmistrz** [comment]
Are you sure this should be issue #4 and not #67?

**Comment by marmistrz** [comment]
```
Feb 19 09:56:19 Sailfish lipstick[3846]: [W] unknown:49 - file:///usr/share/lipstick-glacier-home-qt5/qml/DeviceLockUI.qml:49:9: Cannot assign to non-existent property "onError" 
```

**Comment by neochapay** [comment]
@marmistrz wrong file...plz recheck. Sorry.

**Comment by marmistrz** [comment]
@neochapay should I still test it when we have #69?

**Pull request closed without merging**
