### PR TITLE
Fix bluetooth agent imports and BluezQt usage

### PR DESCRIPTION
**Pull request by PureTryOut**
This makes it build with Qt 5.14 and BluezQt 5.68.0 at least.

### CODE REVIEW

**Comment by neochapay** [comment]
need to add 
BuildRequires:  pkgconfig(KF5BluezQt) >= 5.68.0

And it's broke all bluez4 devices like nexus5

**Comment by PureTryOut** [comment]
Well I don't think this requires >= 5.68.0, but it definitely requires a higher version than whatever you had installed before. I'm not sure in which version the API changed to be honest. I'll just set it to 5.68.0 for now.

The Nexus 5 is a bad example as it runs fine on mainline (iirc just audio doesn't work), so there is no need for a libhybris port and an old kernel.

For officially SailfishOS supported devices just the Jolla 1 uses Bluez4, is that a device you still want to support? Supporting up-to-date BluezQt versions allows Glacier working on way more systems, including postmarketOS and all the devices it supports.

**Comment by PureTryOut** [comment]
Actually, once CMake support is in, I can probably make it work on both Bluez 4 and Bluez 5 by adding a define. That is, if you really want to support Bluez 4. What is the last BluezQt version that supports it?

**Comment by neochapay** [comment]
I think will be better make it working with old and new bluezqt like as https://github.com/nemomobile-ux/glacier-home/blob/devel/src/main.cpp#L55 
And need to resolve conflicts ^_^

**Comment by PureTryOut** [comment]
Yes that is what I meant. Once the CMake change is merged I'll look into it.

**Comment by PureTryOut** [comment]
Ok I just made this MR depend on #126, makes stuff easier.

This currently compiles fine with at least BluezQt 5.68.0 (and probably a bit older but I'm not sure which versions changed waht so I check for 5.68.0 and newer) and Qt 5.14.2, but should also work with BluezQt 5.50.0 which @neochapay is still using.

**Comment by PureTryOut** [comment]
Wait, why did you close this?

**Comment by neochapay** [comment]
Devel branch is deleted and merged into master.

**Pull request closed without merging**
